# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank='False', verbose_name='Название офиса')),
                ('address_city', models.TextField(blank='True', null=True, verbose_name='Адрес офиса')),
                ('address_street', models.TextField(blank='True', null=True, verbose_name='Адрес офиса')),
                ('mail', models.TextField(blank='True', null=True, verbose_name='Email')),
                ('phone', models.TextField(blank='True', null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
                'db_table': 'contacts',
            },
        ),
    ]
