# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_city',
            field=models.TextField(blank='True', null=True, verbose_name='Индекс, город'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_street',
            field=models.TextField(blank='True', null=True, verbose_name='Улица, дом'),
        ),
    ]
