# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank='False', verbose_name='Фамилия и имя')),
                ('city', models.TextField(blank='False', verbose_name='Страна, город')),
                ('nickname', models.TextField(blank='False', verbose_name='Прозвище')),
                ('mail', models.TextField(blank='True', null=True, verbose_name='Email')),
                ('phone', models.TextField(blank='True', null=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, upload_to='author_avatar', verbose_name='Аватар')),
                ('background', models.ImageField(blank=True, upload_to='author_background', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
    ]
