# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
