# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0002_auto_20180916_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_network_1',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 1'),
        ),
        migrations.AddField(
            model_name='author',
            name='social_network_2',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 2'),
        ),
        migrations.AddField(
            model_name='author',
            name='social_network_3',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 3'),
        ),
        migrations.AddField(
            model_name='author',
            name='social_network_4',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 4'),
        ),
        migrations.AddField(
            model_name='author',
            name='social_network_5',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 5'),
        ),
        migrations.AddField(
            model_name='author',
            name='social_network_6',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 6'),
        ),
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='Страна, город'),
        ),
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.CharField(max_length=25, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Фамилия и имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Прозвище'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=25, null=True, verbose_name='Телефон'),
        ),
    ]
