# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0003_auto_20180916_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.CharField(max_length=25, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_1',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 1'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_2',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 2'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_3',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 3'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_4',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 4'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_5',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 5'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_6',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 6'),
        ),
    ]
