# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0007_auto_20180916_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='social_network_1',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 1'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_4',
            field=models.CharField(blank=True, max_length=164, null=True, verbose_name='Социальная сеть 4'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_6',
            field=models.CharField(max_length=164, null=True, verbose_name='Социальная сеть 6'),
        ),
    ]
