# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0008_auto_20180916_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='social_network_1',
            field=models.CharField(max_length=164, verbose_name='Социальная сеть 1'),
        ),
    ]
