# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0015_auto_20180916_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='social_network_2_logo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Логотип 2'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_3_logo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Логотип 3'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_4_logo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Логотип 4'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_5_logo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Логотип 5'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_network_6_logo',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Логотип 6'),
        ),
    ]
