# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0017_auto_20180916_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='social_network_1_logo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='social_network_2_logo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='social_network_3_logo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='social_network_4_logo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='social_network_5_logo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='social_network_6_logo',
        ),
    ]
