# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0018_auto_20180916_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank='True', null=True, verbose_name='Об авторе'),
        ),
    ]
